// File generated by Antigravity AI for Family Health Connect
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCca_biyC_m0UwukPfMBwIPNDTloS1XN9I',
    appId: '1:663207086705:web:5d2a939f506821ce1329d0',
    messagingSenderId: '663207086705',
    projectId: 'family-health-connect',
    authDomain: 'family-health-connect.firebaseapp.com',
    storageBucket: 'family-health-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCca_biyC_m0UwukPfMBwIPNDTloS1XN9I',
    appId: '1:663207086705:android:cebd2ca1ed8f23ca1329d0',
    messagingSenderId: '663207086705',
    projectId: 'family-health-connect',
    storageBucket: 'family-health-connect.firebasestorage.app',
  );
}
