# Generated by Django 6.0.5 on 2026-07-22 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_add_head_role_and_status_to_membership'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='family.familygroup'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('HEALTH', 'Health Alert'), ('REMINDER', 'Reminder'), ('EMERGENCY', 'Emergency SOS'), ('SYSTEM', 'System'), ('FAMILY', 'Family'), ('CHAT', 'Chat'), ('MEDICINE', 'Medicine'), ('WATER', 'Water Intake'), ('SLEEP', 'Sleep')], default='SYSTEM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
    ]
