# Generated by Django 6.0.5 on 2026-05-28 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('delete_account_enabled', models.BooleanField(default=True)),
                ('change_password_enabled', models.BooleanField(default=True)),
                ('account_deletion_requested', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications', models.BooleanField(default=True)),
                ('medicine_reminders', models.BooleanField(default=True)),
                ('health_reminders', models.BooleanField(default=True)),
                ('emergency_alerts', models.BooleanField(default=True)),
                ('family_notifications', models.BooleanField(default=True)),
                ('chat_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY', 'Family Only'), ('PRIVATE', 'Private')], default='FAMILY', max_length=10)),
                ('health_data_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY', 'Family Only'), ('PRIVATE', 'Private')], default='FAMILY', max_length=10)),
                ('family_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY', 'Family Only'), ('PRIVATE', 'Private')], default='FAMILY', max_length=10)),
                ('location_sharing', models.BooleanField(default=True)),
                ('emergency_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY', 'Family Only'), ('PRIVATE', 'Private')], default='FAMILY', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('theme_color', models.CharField(choices=[('blue', 'Blue'), ('emerald', 'Emerald'), ('indigo', 'Indigo'), ('rose', 'Rose'), ('violet', 'Violet'), ('orange', 'Orange')], default='blue', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
