# Generated by Django 6.0.5 on 2026-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacysettings',
            name='share_blood_pressure',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='share_calories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='share_heart_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='share_sleep',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='share_spo2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='share_steps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='share_weight',
            field=models.BooleanField(default=True),
        ),
    ]
