# Generated by Django 6.0.5 on 2026-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_privacysettings_share_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilesettings',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
