# Generated by Django 6.0.5 on 2026-05-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='family.familygroup'),
        ),
    ]
