# Generated by Django 6.0.5 on 2026-05-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_description_conversation_group_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
    ]
