# Generated by Django 6.0.5 on 2026-05-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembership',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='label',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('ELDER', 'Elder'), ('SPOUSE', 'Spouse'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.FloatField(default=100.0)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_zones', to='family.familygroup')),
            ],
        ),
    ]
