# Generated by Django 6.0.5 on 2026-07-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_familygroup_description_familygroup_family_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='label',
            field=models.CharField(choices=[('HEAD', 'Family Head'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('ELDER', 'Elder'), ('SPOUSE', 'Spouse'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
