# Generated by Django 6.0.5 on 2026-05-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_UPDATE', 'Profile Update'), ('FAMILY_JOIN', 'Join Family Group'), ('FAMILY_LEAVE', 'Leave Family Group'), ('DATA_ACCESS', 'Health Data Access'), ('DATA_UPDATE', 'Health Data Update'), ('SOS_TRIGGER', 'Emergency SOS Trigger'), ('SETTINGS_CHANGE', 'Security Settings Change')], max_length=20),
        ),
    ]
