# Generated by Django 6.0.5 on 2026-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
