# Generated by Django 6.0.5 on 2026-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_otp_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhistory',
            name='battery_level',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='is_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
