# Generated by Django 6.0.5 on 2026-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_locationhistory_battery_level_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['user', '-timestamp'], name='users_locat_user_id_635132_idx'),
        ),
    ]
