# Generated by Django 6.0 on 2026-09-17
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text="Amount, e.g. '500' or '1'", max_length=50)),
                ('dosage_unit', models.CharField(default='Tablet', help_text='e.g. Tablet, Capsule, mL, Drops', max_length=50)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once Daily'), ('TWICE_DAILY', 'Twice Daily'), ('THREE_TIMES_DAILY', 'Three Times Daily'), ('CUSTOM', 'Custom')], default='ONCE_DAILY', max_length=50)),
                ('reminder_times', models.JSONField(default=list, help_text="List of HH:MM strings, e.g. ['08:00', '20:00']")),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text="Instructions, e.g. 'Take after food'")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineDoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('dose_time', models.CharField(help_text='HH:MM formatted dose time', max_length=10)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('MISSED', 'Missed')], default='TAKEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_dose_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
                'constraints': [
                    models.UniqueConstraint(fields=('medicine', 'scheduled_date', 'dose_time'), name='unique_medicine_scheduled_dose_log'),
                ],
            },
        ),
    ]
