# Generated by Django 6.0.5 on 2026-05-28 02:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_health_records_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='oxygen_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='stress_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
