# Generated by Django 6.0.5 on 2026-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='vitals_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
