# Generated by Django 6.0.5 on 2026-05-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_sosalert_vitals_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_km', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='sosalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='message',
            field=models.TextField(blank=True, default='Emergency! I need help immediately.', null=True),
        ),
    ]
