# Generated by Django 6.0.5 on 2026-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('HEART_RATE', 'Heart Rate'), ('STEPS', 'Steps'), ('SLEEP', 'Sleep Score'), ('HYDRATION', 'Hydration (L)'), ('CALORIES', 'Calories Burned'), ('OXYGEN', 'Oxygen Level (%)'), ('STRESS', 'Stress Level'), ('BLOOD_PRESSURE', 'Blood Pressure')], max_length=20),
        ),
    ]
