# Generated by Django 6.0.5 on 2026-07-12 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_healthmetric_metric_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='healthalert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_HR', 'High Heart Rate'), ('LOW_HR', 'Low Heart Rate'), ('LOW_SPO2', 'Low Blood Oxygen'), ('INACTIVITY', 'Extended Inactivity'), ('GENERAL', 'General Alert')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='healthalert',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10),
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_goal', models.IntegerField(default=10000)),
                ('calories_goal', models.FloatField(default=2000)),
                ('hydration_goal', models.FloatField(default=2.0)),
                ('sleep_goal', models.FloatField(default=8.0)),
                ('distance_goal', models.FloatField(default=5.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('HEALTH_CONNECT', 'Android Health Connect'), ('WEARABLE', 'Wearable Device')], default='MANUAL', max_length=20)),
                ('heart_rate', models.FloatField(blank=True, help_text='bpm', null=True)),
                ('steps', models.IntegerField(blank=True, help_text='step count', null=True)),
                ('calories', models.FloatField(blank=True, help_text='kcal burned', null=True)),
                ('distance', models.FloatField(blank=True, help_text='km', null=True)),
                ('sleep_hours', models.FloatField(blank=True, help_text='hours of sleep', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='blood oxygen %', null=True)),
                ('hydration', models.FloatField(blank=True, help_text='litres of water', null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='cm', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='healthalert',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.healthsnapshot'),
        ),
        migrations.AddIndex(
            model_name='healthsnapshot',
            index=models.Index(fields=['user', 'recorded_at'], name='health_heal_user_id_f5da66_idx'),
        ),
    ]
