# Generated by Django 6.0.5 on 2026-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_healthalert_options_healthalert_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('HEART_RATE', 'Heart Rate'), ('STEPS', 'Steps'), ('SLEEP', 'Sleep Score'), ('HYDRATION', 'Hydration (L)'), ('CALORIES', 'Calories Burned'), ('OXYGEN', 'Oxygen Level (%)'), ('STRESS', 'Stress Level'), ('BLOOD_PRESSURE', 'Blood Pressure'), ('DISTANCE', 'Distance (km)'), ('BLOOD_PRESSURE_SYSTOLIC', 'Systolic Blood Pressure'), ('BLOOD_PRESSURE_DIASTOLIC', 'Diastolic Blood Pressure'), ('WEIGHT', 'Weight (kg)')], max_length=30),
        ),
    ]
