# Generated by Django 6.0.5 on 2026-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_medicationreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsnapshot',
            name='body_fat',
            field=models.FloatField(blank=True, help_text='body fat %', null=True),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='exercise_count',
            field=models.IntegerField(default=0, help_text='number of exercise sessions'),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='sleep_awake',
            field=models.FloatField(blank=True, help_text='hours of awake time', null=True),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='sleep_deep',
            field=models.FloatField(blank=True, help_text='hours of deep sleep', null=True),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='sleep_light',
            field=models.FloatField(blank=True, help_text='hours of light sleep', null=True),
        ),
        migrations.AddField(
            model_name='healthsnapshot',
            name='sleep_rem',
            field=models.FloatField(blank=True, help_text='hours of REM sleep', null=True),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_HR', 'High Heart Rate'), ('LOW_HR', 'Low Heart Rate'), ('LOW_SPO2', 'Low Blood Oxygen'), ('INACTIVITY', 'Extended Inactivity'), ('GENERAL', 'General Alert'), ('HIGH_BP', 'High Blood Pressure'), ('LOW_STEPS', 'Missed Step Goal'), ('POOR_SLEEP', 'Poor Sleep')], default='GENERAL', max_length=20),
        ),
    ]
