# Generated by Django 6.0.5 on 2026-05-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GOOGLE_FIT', 'Google Fit'), ('APPLE_HEALTH', 'Apple Health'), ('FITBIT', 'Fitbit'), ('GARMIN', 'Garmin')], max_length=20)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('data_points_synced', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
